# Generated by Django 5.0.7 on 2024-08-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coach",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="coach",
            name="official_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
