# Generated by Django 5.0.7 on 2024-08-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpc", "0002_remove_coach_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="description",
        ),
        migrations.AddField(
            model_name="contest",
            name="code",
            field=models.CharField(default="UNKNOWN", max_length=10),
        ),
        migrations.AddField(
            model_name="contest",
            name="color",
            field=models.CharField(default="UNKNOWN", max_length=7),
        ),
        migrations.AlterField(
            model_name="contest",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="document_upload/"),
        ),
    ]
