# Generated by Django 5.0.7 on 2024-08-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpc", "0003_remove_contest_description_contest_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="code",
        ),
        migrations.AlterField(
            model_name="contest",
            name="color",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
