# Generated by Django 5.0.7 on 2024-08-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpc", "0004_remove_contest_code_alter_contest_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
